CREATE TABLE `user` (
		  `id` int(11) NOT NULL AUTO_INCREMENT,
		  `first_name` varchar(50) NOT NULL,
		  `last_name` varchar(50) NOT NULL,
		  `email` varchar(100) NOT NULL,
		  `password` varchar(30) NOT NULL,
		  `secondary_email` varchar(100) DEFAULT NULL,
		  `phone` varchar(20) DEFAULT NULL,
		  `fiscal_code` varchar(16) DEFAULT NULL,
		  `birth_date` date DEFAULT NULL,
		  `birth_place` varchar(50) DEFAULT NULL,
		  `nationality` varchar(30) DEFAULT NULL,
		  `document` varchar(50) DEFAULT NULL,
		  `id_skype` varchar(100) DEFAULT NULL,
		  `admin` bit(1) DEFAULT NULL,
		  `archive_date` date DEFAULT NULL,
		  `note` varchar(255) DEFAULT NULL,
		  PRIMARY KEY (`id_user`),
		  UNIQUE KEY `email` (`email`),
		  UNIQUE KEY `fiscal_code` (`fiscal_code`),
		  UNIQUE KEY `document` (`document`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci